version: '3.5'

services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/RestApi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  database:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: RestApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456123